# @format

services:
  nginx:
    image: nginx:1.29.5-alpine
    mem_limit: 256m
    restart: always
    volumes:
      - ./nginx/cache:/var/www/cache:rw
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  meilisearch:
    image: getmeili/meilisearch:v1.38
    mem_limit: 512m
    healthcheck:
      test: set -o pipefail;curl -fsS http://localhost:7700/health | grep -q '{"status":"available"}'
      retries: 3
      timeout: 5s
    volumes:
      - ./meili_data:/meili_data
    env_file:
      - .env
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_EXPERIMENTAL_REDUCE_INDEXING_MEMORY_USAGE
      - MEILI_EXPERIMENTAL_DUMPLESS_UPGRADE

  botge:
    depends_on:
      - nginx
      - meilisearch
    # Uncomment image, comment build and context for non-local compose.
    # image: ghcr.io/tresster/botge:main
    build:
      context: .
    mem_limit: 512m
    restart: always
    volumes:
      - ./data:/app/data
      - ./tmp:/app/tmp
    env_file:
      - .env
    environment:
      # Node
      - NODE_ENV=production

      # MeiliSearch
      - MEILISEARCH_HOST=http://meilisearch:7700

      # NGINX
      - LOCAL_CACHE_BASE=http://nginx:80

      # Miscellaneous
      - UPDATE_CLIPS_ON_STARTUP=false
      - JOIN_VOICE_CHANNEL=false
